name: Build and Test

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      working-directory: ../../API/SimplyRecruitAPI/SimplyRecruitAPI
      run: dotnet restore
    - name: Build
      working-directory: ../../API/SimplyRecruitAPI/SimplyRecruitAPI
      run: dotnet build --configuration Release

  test:
    runs-on: windows-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      working-directory: ../../API/SimplyRecruitAPI/SimplyRecruitAPITests
      run: dotnet restore
    - name: Run Tests
      working-directory: ../../API/SimplyRecruitAPI/SimplyRecruitAPITests
      run: dotnet test --no-restore --verbosity normal
